name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make linux
  build-musl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: musl musl-dev musl-tools
        version: 1.0
    - name: build-musl 
      run: make linux-musl
    
